<?php

namespace Modules\Starter\Enums;

enum State: string
{
	const SUCCESS = 'STATE_CODE_SUCCESS';
	const FAIL = 'STATE_CODE_FAIL';
	const DB_FAIL = 'STATE_CODE_DB_FAIL';
	const NOT_LOGIN = 'STATE_CODE_NOT_LOGIN';
	const NOT_FOUND = 'STATE_CODE_NOT_FOUND';
	const NOT_ALLOWED = 'STATE_CODE_NOT_ALLOWED';
	const INVALID_PARAMETERS = 'STATE_CODE_INVALID_PARAMETERS';
	const DUPLICATION = 'STATE_CODE_DUPLICATION';
	const USER_INVALID = 'STATE_CODE_USER_INVALID';
	const USER_INFO_INCOMPLETE = 'STATE_CODE_USER_INFO_INCOMPLETE';
	const TOO_FREQUENTLY = 'STATE_CODE_TOO_FREQUENTLY';
	const CAPTCHA_ERROR = 'STATE_CODE_CAPTCHA_ERROR';
	const VERIFY_ERROR = 'STATE_CODE_VERIFY_ERROR';
	const MOBILE_ERROR = 'STATE_CODE_MOBILE_ERROR';
	const EMAIL_ERROR = 'STATE_CODE_EMAIL_ERROR';
	const RISKY_CONTENT = 'STATE_CODE_RISKY_CONTENT';
	const RISKY_IMAGE = 'STATE_CODE_RISKY_IMAGE';
}
